concepts/urls.py
from django.urls import path
from . import views

app_name = "concepts"
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('about', views.AboutView.as_view(), name='about'),
    path('search', views.SearchView.as_view(), name='search'),
]

parmesan2/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path(settings.URL_PREFIX + 'admin/', admin.site.urls),
    path(settings.URL_PREFIX + 'haystack/', include('haystack.urls')),
    path(settings.URL_PREFIX + '', include('concepts.urls')),
]

concepts/models.py
from django.db import models
from django.utils.translation import gettext as _

class Author(models.Model):
    """
    Represents the author of one or more documents in a corpus.
    """

    #: The author's first name.
    first_name = models.CharField(_("first name"), max_length=100, blank=False,
            null=False)

    #: The author's last name. 
    last_name = models.CharField(_("last name"), max_length=1000, blank=True)

class Collection(models.Model):
    """
    Represents a collection of documents in the corpus. Collections can be
    thought of as high-level contexts in which terms may appear; it is more
    likely that the usage of a term will vary form context to context rather
    than from document to document.
    """

    #: The human-readable name of the collection.
    name = models.CharField(_("name"), max_length=500, blank=False, null=False,
            unique=True)

    #: A free-form description of the collection.
    description = models.TextField(_("description"), blank=True)

    #: The priority of this collection; higher-priority collections are
    #: displayed first.
    priority = models.IntegerField(_('priority'), null=False, default=0)

    def __str__(self):

        return self.name

class Document(models.Model):
    """
    Represents a single document in the corpus. Documents are not further
    subdivided into sections or subsections.
    """

    #: The title of the document.
    title = models.CharField(_("title"), max_length=500, blank=False,
            null=False)

    #: The authors of the document.
    authors = models.ManyToManyField('Author', verbose_name=_("authors"),
            blank=True)

    #: A URL to the original document.
    url = models.URLField(_("URL"), blank=True)

    #: The document's publication date.
    pub_date = models.DateField(_("publication date"), blank=True, null=True)

    #: The colleciton this document appears in.
    collection = models.ForeignKey('Collection', verbose_name=_("collection"),
            blank=False, null=False, on_delete=models.CASCADE)

    def __str__(self):

        return self.title

class Sentence(models.Model):
    """
    Represents a normalized sentence within a document.
    """

    #: The document containing this sentence.
    document = models.ForeignKey('Document', verbose_name=_("document"),
            on_delete=models.CASCADE)

    #: The text of the sentence.
    text = models.TextField(_("text"), blank=False)

    #: The list of lemmas in the sentence.
    lemmas = models.TextField(_("lemmas"), blank=False)

class Token(models.Model):
    """
    Represents a single token in a document.
    """

    #: The sentence that this token appears in.
    sentence = models.ForeignKey('Sentence', verbose_name=_("sentence"),
            on_delete=models.CASCADE, related_name='tokens')

    #: The token's index in the sentence.
    index = models.IntegerField(_("index"))

    #: The token's form.
    form = models.CharField(_("form"), max_length=500)

    #: The token's lemma.
    lemma = models.CharField(_("lemma"), max_length=500)

    #: The token's course-grained POS tag.
    upos = models.CharField(_("UPOS"), max_length=10)

    #: The token's fine-grained POS tag.
    xpos = models.CharField(_("XPOS"), max_length=10)

    #: The token's features.
    features = models.CharField(_("features"), max_length=500, blank=True)

    #: The index of the token's head.
    head = models.IntegerField(_("head"), null=True)

    #: The token's relation to its head.
    deprel = models.CharField(_("deprel"), max_length=500, blank=True)

    #: Miscellaneous features of the word.
    misc = models.CharField(_("misc"), max_length=500, blank=True)

class Term(models.Model):
    """
    Represents a well-formed term. 
    """

    #: The normalized form of the term.
    term = models.CharField(_("term"), max_length=500, blank=False, null=False)

class Definition(models.Model):
    """
    A definition of a term from a particular source.
    """

    #: The term being defined.
    term = models.ForeignKey('Term', verbose_name=_("term"), null=False,
            on_delete=models.CASCADE)

    #: The name of this term, according to the source.
    source_name = models.CharField(_("source name"), max_length=500, blank=False, null=False)

    #: The definition of the term.
    definition = models.TextField(_("definition"), blank=False, null=False)

    #: The source of the definition.
    source = models.ForeignKey('Source', verbose_name=_("source"), null=True,
            on_delete=models.SET_NULL)

    #: The URL to the definition of this term in the given source.
    source_url = models.URLField(_("URL"), blank=True)

    #: The date and time the definition was accessed from the source.
    accessed = models.DateTimeField(_("accessed"), blank=True, null=True,
            auto_now=True)

class Source(models.Model):
    """
    An external source of information about terms and their definitions.
    """

    #: The name of the data source.
    name = models.TextField(_("name"), max_length=500, blank=False)

    #: The home page of this data source.
    home_page = models.URLField(_("home page"), blank=True)

class SourceLink(models.Model):
    """
    Represents a source's information about a particular term.
    """

    #: The term being linked.
    term = models.ForeignKey('Term', verbose_name=_("term"),
            on_delete=models.CASCADE)

    #: The source linking this term.
    source = models.ForeignKey('Source', verbose_name=_("source"),
            on_delete=models.CASCADE)

    #: A link to the source's information about the given term.
    link = models.URLField(_("link"), blank=False)

class Query(models.Model):
    """
    Represents the set of queries that have been made. 
    """

    query = models.TextField(_("query"), blank=False, null=False)

    count = models.IntegerField(_("count"), blank=False, null=False, default=0)

concepts/forms.py
from django import forms
from django.utils.translation import gettext as _
from .models import *

def get_collections():

    return Collection.objects.all()

class SearchForm(forms.Form):
    """
    The default Parmesan search form, which allows the user to construct a
    query for searching data in a contextual corpus.
    """

    template_name = "concepts/search_form.html"

    query = forms.CharField(
        label=_("Query"),
        required=True,
    )

    collections = forms.ModelMultipleChoiceField(
        Collection.objects.all().order_by('-priority'),
        label=_("Collections"),
        initial=Collection.objects.all(),
    )

concepts/views.py
from bs4 import BeautifulSoup
from django.conf import settings
from django.db.models import Case, Count, F, IntegerField, Q, Sum, Value, When
from django.views.generic import TemplateView
from itertools import groupby
from urllib.parse import quote_plus
from .models import *
from .forms import SearchForm

import requests
import spacy
import time

#nlp = spacy.load('en_core_web_trf')

ENDPOINT = "https://query.wikidata.org/sparql"
HEADERS = {
    'User-Agent': 'parmesan/0.2',
}

# MINUS instance of Wikimedia category
# MINUS subclass of concrete object
# MINUS subclass of physical object
# MINUS subclass of geographic region
# MINUS subclass of artistic concept
# MINUS subclass of geographic location
# MINUS subclass of human behavior
# MINUS subclass of point of time
# MINUS subclass of time interval
# MINUS subclass of currency
sparql_query = """
SELECT distinct ?item ?itemLabel ?itemDescription WHERE {
    {?item rdfs:label "%s"@en.} UNION
    {?item skos:altLabel "%s"@en.}
    MINUS { ?item wdt:P31 wd:Q4167836 }
    MINUS { ?item wdt:P279 wd:Q4167836 }
    MINUS { ?item wdt:P279 wd:Q4406616 }
    MINUS { ?item wdt:P279 wd:Q223557 }
    MINUS { ?item wdt:P279 wd:Q82794 }
    MINUS { ?item wdt:P279 wd:Q63539947 }
    MINUS { ?item wdt:P279 wd:Q2221906 }
    MINUS { ?item wdt:P279 wd:Q3769299 }
    MINUS { ?item wdt:P279 wd:Q186408 }
    MINUS { ?item wdt:P279 wd:Q186081 }
    MINUS { ?item wdt:P279 wd:Q8142 }
    SERVICE wikibase:label {
        bd:serviceParam wikibase:language "en" .
    }
}
"""

#class Link:
#
#    def __init__(self, name, source, url, description):
#
#        self.name = name
#        self.source = source
#        self.url = url
#        self.description = description

def extract_definition(response):

    soup = BeautifulSoup(response.text, 'lxml')
    revision = soup.find(id="revision")
    paragraph = revision.find("p").get_text()

    return paragraph

def get_nlab(query):

    nlab_source = Source.objects.get_or_create(
        name="nLab",
    )[0]

    links = Definition.objects.filter(
        term__term=query,
        source=nlab_source,
    )

    if links.count() > 0:
        print("Using cached nLab")
        return links

    try:
        url = "http://ncatlab.org/nlab/show/%s" % quote_plus(query)
        response = requests.get(url)
        if response.status_code == 200:
            term = Term(term=query)
            term.save()
            definition = Definition(
                term=term,
                source_name=query,
                definition=extract_definition(response),
                source=nlab_source,
                source_url=url,
            )
            definition.save()
            return [definition]
        else:
            return []
    except Exception as err:
        print("An error occurred.")
        print(err)
        return []

def get_wikidata(query):

    wikidata_source = Source.objects.get_or_create(
        name="Wikidata",
    )[0]

    links = Definition.objects.filter(
        term__term=query,
        source=wikidata_source,
    )

    if links.count() > 0:
        print("Using cache")
        return links

    try:
        while True:
            print("Querying Wikidata")
            result = requests.post(
                ENDPOINT,
                data={'query': sparql_query % (query, query), 'format': 'json'},
                headers=HEADERS,
            )
            if result.status_code == 429:
                print("Too many requests. Retrying.")
                time.sleep(result.headers['retry-after'])
                continue
            break

        json = result.json()
        links = []
        for item in json['results']['bindings']:
            link = item['item']['value']
            description = item.get('itemDescription', {"value": ""})['value']
            label = item['itemLabel']['value']
            term = Term(term=label)
            term.save()
            definition = Definition(
                term=term,
                source_name=label,
                definition=description,
                source=wikidata_source,
                source_url=link,
            )
            #definition.save()
            links.append(definition)
        return links
    except Exception as err:
        print("An exception occurred.")
        print(err)
        return []

class IndexView(TemplateView):

    template_name = 'concepts/index.html'

    def get_context_data(self, **kwargs):

        context = super().get_context_data(**kwargs)
        context['form'] = SearchForm()

        return context

class QueryResults:

    def __init__(self, documents, query):

        self.documents = documents
        self.query = query

    def get_documents(self):

        regex = settings.SEARCH_REGEX

        for document in self.documents:

            sentences = Sentence.objects.filter(
                document=document,
                lemmas__iregex=regex % self.query,
            )[:10]

            yield QueryResult(
                document,
                sentences,
                self.query,
            )

class QueryResult:

    def __init__(self, document, sentences, query):

        self.document = document
        self.sentences = sentences
        self.query = query

class SearchView(TemplateView):

    template_name = 'concepts/results.html'

    def get_context_data(self, **kwargs):

        context = super().get_context_data(**kwargs)
        
        regex = settings.SEARCH_REGEX

        form = SearchForm(self.request.GET)
        if form.is_valid():
            collections = form.cleaned_data['collections']
            query = form.cleaned_data['query']
            query_record = Query.objects.get_or_create(
                query=query,
            )[0]
            query_record.count += 1
            query_record.save()
            #parsed_query = nlp(query)
            #lemmatized_query = ' '.join([token.lemma_ for token in
            #    query])
            results = []
            total_count = 0
            for collection in collections:
                documents = Document.objects.filter(
                    sentence__lemmas__iregex=regex % query,
                    collection=collection,
                ).distinct().annotate(
                    num_sentences=Count("sentence", filter=Q(sentence__lemmas__iregex=regex % query)),
                ).annotate(
                    title_match=Case(
                        When(title__iregex=regex % query, then=Value(10)),
                        default=Value(0),
                        output_field=IntegerField(),
                    ),
                ).annotate(
                    total_score=F('num_sentences') + F('title_match'),
                ).order_by('-total_score')
                count = documents.count()
                total_count += count
                results.append((collection, QueryResults(documents[:10],
                    query), count))

            context['links'] = list(get_wikidata(query)[:5]) + list(get_nlab(query)[:5])
            context['results'] = results
            context['form'] = form
            context['query'] = query
            context['total_count'] = total_count

            return context
        else:
            context['results'] = []
            context['form'] = form
            context['query'] = "No query given"
            context['total_count'] = 0

            return context

class AboutView(TemplateView):

    template_name = 'concepts/about.html'

concepts/templates/concepts/about.html
{% extends 'concepts/base.html' %}

{% load i18n static %}

{% block description %}
{% trans "About the Parmesan mathematical search system" %}
{% endblock %}

{% block author %}
{% trans "Jacob Collard" %}
{% endblock %}

{% block title %}
{% trans "About Parmesan" %}
{% endblock %}

{% block css %}
<link rel="stylesheet" href="{% static 'concepts/css/search.css' %}?v=1.2">
{% endblock %}

{% block content %}
<main role="main" class="container">
  <h1 class="vertical-center">
    {% trans "About Parmesan" %}
  </h1>
  <p>
  {% blocktrans %}
  Parmesan (PARsing Mathematical Entities Search And Navigation) is an
  experimental search system for mathematical concepts, specifically in
  category theory. The system was created in 2023 by Jacob Collard, Valeria de
  Paiva, and Eswaran Subrahmanian. The basic idea behind it is that a newcomer
  to the field may come across unfamiliar concepts and wish to find out more
  about them. This isn't limited to just learning their definitions or proofs,
  but also includes finding examples that highlight how they are used in real
  mathematical texts.
  {% endblocktrans %}
  </p>

  <p>
  {% blocktrans %}
  Parmesan has been presented at two scientific conferences: 
  <a href="http://noisy-text.github.io/2022/">W-NUT 2022</a> and 
  <a href="https://lexicala.com/4lr/">4LR 2023</a>. Correspondingly, we have
  two preprints describing the functionality of Parmesan as well as our broader
  findings on working with mathematical text. Both of these are available on
  arXiv. 
  {% endblocktrans %}
  </p>

  <ul>
    <li>
      Jacob Collard, Valeria de Paiva, Brendan Fong, and Eswaran Subrahmanian.
      2022. Extracting Mathematical Concepts from Text. ArXiv preprint. 
      <a href="https://arxiv.org/abs/2208.13830">2208.13830</a>.
    </li>
    <li>
      Jacob Collard, Valeria de Paiva, Eswaran Subrahmanian.
      2023. Parmesan: mathematical concept extraction for education. ArXiv
      preprint. <a href="https://arxiv.org/abs/2307.06699">2307.06699</a>.
    </li>
  </ul>

  <p>
  {% blocktrans %}
  The presentation at W-NUT 2022 is available as a recorded video, presented by
  Jacob Collard. 
  {% endblocktrans %}
  </p>

  <iframe style="display: block; margin: 1em auto;" width="650" height="400" src="https://www.youtube-nocookie.com/embed/-ZhZjMn1Zpk" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen="">
</iframe>
</main>
{% endblock %}

concepts/templates/concepts/base.html
{% load bootstrap5 i18n static %}

{% get_current_language as LANGUAGE_CODE %}

<!doctype html>
<html lang="{{ LANGUAGE_CODE }}">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description"
          content="{% block description %}{% endblock %}">
    <meta name="author"
          content="{% block author %}{% trans "Jacob Collard" %}{% endblock %}">

    <title>{% block title %}{% trans "Parmesan" %}{% endblock %}</title>

    {% bootstrap_css %}
    {% bootstrap_javascript %}
    
    {% block css %}
    {% endblock %}
  </head>

  <body>
    {% bootstrap_messages %}

    {% include "concepts/navbar.html" %}

    {% block content %}
    {% endblock %}

    <div class="container">
      <footer class="py-3 my-4">
        <p class="text-center text-muted border-top py-2">
        Comments? Questions? 
        <a href="mailto:valeria@topos.institute">Contact us</a>
        </p>
      </footer>
    </div>
  </body>
</html>

concepts/templates/concepts/index.html
{% extends 'concepts/base.html' %}

{% load i18n static %}

{% block description %}
{% trans "Search for mathematical concepts, definitions, and relations." %}
{% endblock %}

{% block author %}
{% trans "Jacob Collard" %}
{% endblock %}

{% block title %}
{% trans "Parmesan" %}
{% endblock %}

{% block css %}
<link rel="stylesheet" href="{% static 'concepts/css/search.css' %}?v=1.2">
{% endblock %}

{% block content %}
<main role="main" class="container">
  <div class="center-form vertical-center">
    <div class="text-center">
      <div class="center-title">
        <h1>&#x1f9c0; {% trans "Parmesan 0.2" %}</h1>
        <h2 class="fs-5">PARsing Mathematical Entities Search And Navigation</h2>
      </div>

      <p>
      Search the name of a mathematical concept to find information about its
      definition and examples of usage.
      </p>
    </div>

    <form action="{% url "concepts:search" %}" method="get">
      {% include "concepts/search_form.html" with form=form %}
    </form>
  </div>
</main>
{% endblock %}

concepts/templates/concepts/navbar.html
{% load i18n %}

<nav class="py-2 bg-light border-bottom">
  <div class="container d-flex flex-wrap">
    <ul class="nav me-auto">
      <li class="nav-item">
        <a href="{% url "concepts:index" %}"
           class="nav-link link-dark px-2">
          {% trans "Home" %}
        </a>
      </li>
      <li class="nav-item">
        <a href="{% url "concepts:about" %}"
           class="nav-link link-dark px-2">
          {% trans "About" %}
        </a>
      </li>
    </ul>
  </div>
</nav>

concepts/templates/concepts/results.html
{% extends 'concepts/base.html' %}

{% load i18n highlight static %}

{% block description %}
{% trans "Search for mathematical concepts, definitions, and relations." %}
{% endblock %}

{% block author %}
{% trans "Jacob Collard" %}
{% endblock %}

{% block title %}
{% trans "Parmesan | Search Results" %}
{% endblock %}

{% block css %}
<link rel="stylesheet" href="{% static 'concepts/css/search.css' %}?v=1.2">
{% endblock %}

{% block content %}
<main role="main" class="container">
  <div class="center-form near-top">
    <div class="text-center center-title">
      <h1>&#x1f9c0; {% trans "Parmesan 0.2" %}</h1>
    </div>
    <form action="{% url "concepts:search" %}" method="get">
      {% include "concepts/search_form.html" with form=form %}
    </form>
  </div>

  {% if links %}
    <div>
      <h2>{% trans "Knowledge Base" %}</h2>
      <p>
      {% blocktrans %}
      This is our best guess as to your search term's value in external
      knowledge bases, such as <a href="https://wikidata.org">Wikidata</a> and 
      <a href="https://ncatlab.org">nLab</a>.
      {% endblocktrans %}
      </p>
      <div class="row row-cols-1 row-cols-sm-5 g-4">
        {% for link in links %}
          <div class="col">
            <div class="card h-100">
              <div class="card-body">
                <h5 class="card-title">
                  <a href="{{ link.source_url }}">
                    {{ link.source_name|title }}
                  </a>
                </h5>
                <h6 class="card-subtitle mb-2 text-muted">
                  {{ link.source.name }}
                </h6>
                <p class="card-text">
                  {{ link.definition }}
                </p>
              </div>
            </div>
          </div>
        {% endfor %}
      </div>
    </div>
  {% endif %}

  <hr/>

  <h2>{% trans "Corpora" %}</h2>

  <p>
  {% blocktrans with query=query count total_count=total_count %}
  Your search for "{{ query}}" produced <b>{{ total_count }}</b> total result.
  {% plural %}
  Your search for "{{ query }}" produced <b>{{ total_count }}</b> total results.
  {% endblocktrans %}

  {% blocktrans %}
  These results are examples of use in key category theory datasets.
  {% endblocktrans %}
  </p>

  <div class="accordion" id="search-results">
    {% for result in results %}
      <div class="accordion-item">
        <h2 class="accordion-header" id="collection-{{ forloop.counter }}">
          <button class="accordion-button collapsed"
                  type="button"
                  data-bs-toggle="collapse"
                  data-bs-target="#collection-content-{{ forloop.counter }}"
                  aria-expanded="false"
                  aria-controls="collection-content-{{ forloop.counter }}">
            {{ result.0.name }}
            {% with result.2 as count %}
            {% with result.1.documents|length as n %}
              {% blocktrans with n=n count count=count %}
              (displaying {{ n }} of {{ count }} result)
              {% plural %}
              (displaying {{ n }} of {{ count }} results)
              {% endblocktrans %}
            {% endwith %}
            {% endwith %}
          </button>
        </h2>
        <div id="collection-content-{{ forloop.counter }}"
             class="accordion-collapse collapse"
             aria-labelledby="collection-{{ forloop.counter }}"
             data-bs-parent="#search-results">
          <div class="accordion-body">
            {% for query_result in result.1.get_documents %}
              <div class="card search-result-card">
                <div class="card-header">
                  {% if query_result.document.url %}
                    <a href="{{ query_result.document.url }}">
                      {{ query_result.document.title }}
                    </a>
                  {% else %}
                    {{ query_result.document.title }}
                  {% endif %}
                </div>
                <div class="card-body">
                  <p class="card-text">
                    <ul>
                      {% for sentence in query_result.sentences %}
                        <li>
                          {% highlight sentence query %}
                        </li>
                      {% endfor %}
                    </ul>
                    {% comment %}
                    {% highlight query_result.document.text with query html_tag "mark" %}
                    {% endcomment %}
                  </p>
                </div>
              </div>
            {% endfor %}
          </div>
        </div>
      </div>
    {% endfor %}
  </div>
</main>
{% endblock %}

concepts/templates/concepts/search_form.html
{% load i18n widget_tweaks %}

{{ form.non_field_errors }}
<div class="row justify-content-sm-center">
  <div class="col-6">
    {{ form.query.errors }}
    <input type="text"
           id="search-bar"
           name="query"
           class="form-control"
           placeholder="{% trans "Enter a phrase, such as 'closed category'." %}"
           required>
    <div class="accordion advanced-search" id="advanced-search">
      <div class="accordion-item">
        <h2 class="accordion-header" id="advanced-search-header">
          <button class="accordion-button collapsed"
                  type="button"
                  data-bs-toggle="collapse"
                  data-bs-target="#advanced-search-content"
                  aria-expanded="false"
                  aria-controls="advanced-search-content">
            {% trans "Advanced Options" %}
          </button>
        </h2>
        <div id="advanced-search-content"
             class="accordion-collapse collapse"
             aria-labelledby="advanced-search-header"
             data-bs-parent="#advanced-search">
          <div class="accordion-body">
            <label for="{{ form.collections.id_for_label }}" class="form-label">
              {% trans "Collections" %}
            </label>
            {% render_field form.collections class+="form-select" %}
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="col-auto">
    <button type="submit" class="btn btn-primary">
      {% trans "Search" %}
    </button>
  </div>
</div>